spring:
    profiles:
        active: development

management:
    context-path: /

---
debug: true
spring:
    profiles: development
    jpa:
        generate-ddl: true


---
spring:
    profiles: production
    datasource:
        url: jdbc:mysql://www.zhongerp.com/wenhua
        username: wenhua
        password: wenhua123456
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
