spring:
    profiles:
        active: development

---
debug: true
spring:
    profiles: development
    jpa:
        generate-ddl: true

---
spring:
    profiles: production
    main:
        show_banner: false
    datasource:
        url: jdbc:mysql://hostname/db
        username: user
        password: password
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: validate

server:
    port: 80
