spring:
    profiles:
        active: development

management:
    context-path: /actuator

---
debug: true
spring:
    profiles: development
    jpa:
        generate-ddl: true

---
spring:
    profiles: production
    datasource:
        url: jdbc:mysql://121.43.109.196/wenhua
        username: root
        password: wenhuawenhua
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
