spring:
    profiles:
        active: development

management:
    context-path: /actuator

ueditor:
    config:
        json:
            path: 'classpath:UEConfig.json'

---
debug: true
spring:
    profiles: development
    jpa:
        generate-ddl: true

---
spring:
    profiles: production
    datasource:
        url: jdbc:mysql://121.43.109.196/wenhua?useUnicode=yes&characterEncoding=UTF-8
        username: root
        password: wenhuawenhua
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
