INSERT INTO account (`USERNAME`, `PASSWORD`, `ENABLE`, `CREATED_AT`, `CREATED_BY`, `REFERENCE_ID`, `CREDENTIALS_EXPIRED`, `EXPIRED`, `LOCKED`)
VALUES
  ('test', '$2a$10$rjvoBv./ZCCHACKYhuT3P..7gPrGcjTCCFOh7aqYxX7egeomE8TpW', TRUE, NOW(), 'init', 'init', FALSE, FALSE,
   FALSE);

INSERT INTO role (`ID`, `CODE`, `LABEL`, `ORDINAL`, `EFFECTIVE_AT`, `EXPIRES_AT`, `CREATED_AT`)
VALUES
  (1, 'ADMIN', 'Admin', 1, '2016-01-01 00:00:00', NULL, NOW()),
  (2, 'USER', 'user', 2, '2016-01-01 00:00:00', NULL, NOW());

INSERT INTO account_roles (`ACCOUNT_ID`, `ROLES_ID`)
VALUES
  (1, 1),
  (1, 2);